services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: OPENAI_API_KEY
        value: <sk-QeFVXulFFgfd07PE8jgkKqQkv-lWBUu1T7LSQDGkcxT3BlbkFJXkqfnG00x2jCjd-YwDCJEDx-9YajBpEdMQV4HMxkgA>
      - key: TELEGRAM_TOKEN
        value: <6476507346:AAFs7OxBI6wDrigeYhblqRu948A8lfZsibk>
      - key: GOOGLE_SHEETS_CREDENTIALS
        value: <AIzaSyB1p_lmIlgz7OaUu6MolYsLXY-io4xXG4Q>
    autoDeploy: true
